import * as fs from 'fs';
import * as path from 'path';
import {
  Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType,
  Table, TableRow, TableCell, WidthType, BorderStyle, PageBreak,
  Footer, PageNumber, ShadingType, LevelFormat, convertInchesToTwip,
} from 'docx';
import type { ReportData, ReportControlRow } from '../services/reports/aggregate.js';

/**
 * Phase 8C — Audit-grade DOCX report.
 *
 * Mirrors the PDF content but in Word's native format so auditors can
 * annotate and redistribute. Uses the `docx` library's Packer API to
 * stream the final .docx file.
 */

const COLORS = {
  primary: '1e293b',
  muted: '64748b',
  border: 'cbd5e1',
  green: '16a34a',
  amber: 'd97706',
  red: 'dc2626',
  accent: '4338ca',
  headerBg: 'eef2ff',
};

export interface DocxResult {
  path: string;
  bytes: number;
}

export async function renderAuditReportDocx(
  data: ReportData,
  outputPath: string,
): Promise<DocxResult> {
  const resolved = path.resolve(outputPath);

  const doc = new Document({
    creator: 'Attesting',
    title: `Compliance Audit Report — ${data.catalog.name}`,
    description: `${data.organization.name} / ${data.scope.name}`,
    styles: { default: { document: { run: { font: 'Calibri', size: 22 } } } },
    numbering: {
      config: [
        {
          reference: 'audit-numbered',
          levels: [{ level: 0, format: LevelFormat.DECIMAL, text: '%1.', alignment: AlignmentType.START }],
        },
      ],
    },
    sections: [
      {
        properties: { page: { margin: { top: convertInchesToTwip(1), bottom: convertInchesToTwip(1), left: convertInchesToTwip(1), right: convertInchesToTwip(1) } } },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({ text: `${data.organization.name} · ${data.catalog.short_name} · Page `, size: 16, color: COLORS.muted }),
                  new TextRun({ children: [PageNumber.CURRENT], size: 16, color: COLORS.muted }),
                  new TextRun({ text: ' of ', size: 16, color: COLORS.muted }),
                  new TextRun({ children: [PageNumber.TOTAL_PAGES], size: 16, color: COLORS.muted }),
                ],
              }),
            ],
          }),
        },
        children: [
          ...buildCoverPage(data),
          new Paragraph({ children: [new PageBreak()] }),
          ...buildExecutiveSummary(data),
          new Paragraph({ children: [new PageBreak()] }),
          ...buildControlInventory(data),
          new Paragraph({ children: [new PageBreak()] }),
          ...buildSubsystems(data),
          new Paragraph({ children: [new PageBreak()] }),
          ...buildAppendix(data),
        ],
      },
    ],
  });

  const buffer = await Packer.toBuffer(doc);
  fs.writeFileSync(resolved, buffer);

  return { path: resolved, bytes: buffer.length };
}

// ── Sections ──────────────────────────────────────────────

function buildCoverPage(data: ReportData): Paragraph[] {
  const score = data.score?.overall_score ?? 0;
  return [
    spacer(8),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      heading: HeadingLevel.TITLE,
      children: [new TextRun({ text: 'Compliance Audit Report', bold: true, size: 48, color: COLORS.primary })],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 200 },
      children: [new TextRun({ text: data.catalog.name, size: 28, color: COLORS.muted })],
    }),
    spacer(4),
    kv('Organization', data.organization.name),
    kv('Scope', data.scope.name),
    kv('Catalog', `${data.catalog.name} (${data.catalog.short_name})`),
    kv('Generated', formatDate(data.generated_at)),
    kv('Total Controls', String(data.catalog.total_controls || data.controls.length)),
    spacer(4),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [new TextRun({ text: score.toFixed(0), bold: true, size: 144, color: colorForScore(score) })],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [new TextRun({ text: 'Overall Compliance Score (0–100)', size: 22, color: COLORS.muted })],
    }),
    spacer(6),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [new TextRun({
        text: 'Generated by Attesting. Contains sensitive compliance data.',
        italics: true, size: 18, color: COLORS.muted,
      })],
    }),
  ];
}

function buildExecutiveSummary(data: ReportData): Paragraph[] {
  const s = data.score;
  const out: any[] = [
    heading('1. Executive Summary'),
    keyFigureTable([
      ['Overall Score', (s?.overall_score ?? 0).toFixed(1), colorForScore(s?.overall_score ?? 0)],
      ['Coverage',      (s?.coverage_score ?? 0).toFixed(1), colorForScore(s?.coverage_score ?? 0)],
      ['Evidence',      s?.evidence_score != null ? s.evidence_score.toFixed(1) : 'n/a', colorForScore(s?.evidence_score ?? null)],
      ['Assessment',    s?.assessment_score != null ? s.assessment_score.toFixed(1) : 'n/a', colorForScore(s?.assessment_score ?? null)],
    ]),
    spacer(2),
    subheading('Control Family Breakdown'),
  ];

  const families = data.family_breakdown ?? [];
  if (families.length === 0) {
    out.push(new Paragraph({ children: [new TextRun({ text: 'No family breakdown available.', italics: true, color: COLORS.muted })] }));
  } else {
    out.push(familyBreakdownTable(families.slice(0, 20)));
  }

  out.push(spacer(2));
  out.push(subheading(`Score Trend (${data.trend.length} snapshot${data.trend.length === 1 ? '' : 's'})`));
  if (data.trend.length < 2) {
    out.push(new Paragraph({ children: [new TextRun({ text: 'Not enough history for a trend. Take more snapshots to populate.', italics: true, color: COLORS.muted })] }));
  } else {
    const first = data.trend[0].overall_score;
    const last = data.trend[data.trend.length - 1].overall_score;
    const delta = last - first;
    out.push(new Paragraph({
      children: [
        new TextRun({ text: `From ${formatDate(data.trend[0].calculated_at)} to ${formatDate(data.trend[data.trend.length - 1].calculated_at)}: `, color: COLORS.muted }),
        new TextRun({ text: `${delta >= 0 ? '+' : ''}${delta.toFixed(1)} points`, bold: true, color: delta >= 0 ? COLORS.green : COLORS.red }),
      ],
    }));
    out.push(trendTable(data.trend));
  }

  return out;
}

function buildControlInventory(data: ReportData): any[] {
  return [
    heading('2. Control Inventory'),
    new Paragraph({
      children: [new TextRun({
        text: `${data.controls.length} controls. Status, evidence, and assessment per control.`,
        italics: true, color: COLORS.muted,
      })],
    }),
    spacer(1),
    controlTable(data.controls),
  ];
}

function buildSubsystems(data: ReportData): any[] {
  const es = data.evidence_summary;
  const out: any[] = [
    heading('3. Evidence, Risk & POA&M'),
    subheading('3.1  Evidence Summary'),
    summaryTable([
      ['Total Artifacts',        String(es.total)],
      ['Fresh',                  String(es.fresh)],
      ['Expiring Soon',          String(es.expiring_soon)],
      ['Expired',                String(es.expired)],
      ['Pending Review',         String(es.pending)],
      ['Rejected',               String(es.rejected)],
      ['Controls with Evidence', String(es.controls_with_evidence)],
      ['Controls Missing',       String(es.controls_missing_evidence)],
    ]),
    spacer(2),
    subheading(`3.2  Risk Summary (${data.risks.total_open} open)`),
  ];

  if (data.risks.top.length === 0) {
    out.push(new Paragraph({ children: [new TextRun({ text: 'No open risks.', italics: true, color: COLORS.muted })] }));
  } else {
    out.push(riskTable(data.risks.top));
  }

  out.push(spacer(2));
  out.push(subheading(`3.3  POA&M Items (${data.poam.total_open} open, ${data.poam.overdue} overdue)`));
  if (data.poam.items.length === 0) {
    out.push(new Paragraph({ children: [new TextRun({ text: 'No open POA&M items.', italics: true, color: COLORS.muted })] }));
  } else {
    out.push(poamTable(data.poam.items.slice(0, 25)));
  }

  return out;
}

function buildAppendix(data: ReportData): any[] {
  const m = data.methodology;
  return [
    heading('4. Appendix — Methodology'),
    new Paragraph({ children: [new TextRun({ text: 'Attesting calculates compliance scores using a three-factor weighted formula:' })] }),
    spacer(1),
    new Paragraph({
      children: [new TextRun({
        text: `overall = coverage × ${m.coverage_weight.toFixed(2)} + evidence × ${m.evidence_weight.toFixed(2)} + assessment × ${m.assessment_weight.toFixed(2)}`,
        font: 'Courier New', size: 20,
      })],
    }),
    spacer(1),
    subheading('Coverage Factor Weights'),
    bullet('implemented — 1.00'),
    bullet('alternative — 0.75'),
    bullet('partially-implemented — 0.50'),
    bullet('planned — 0.25'),
    bullet('not-implemented — 0.00'),
    bullet('not-applicable — excluded'),
    spacer(2),
    subheading('Data Provenance'),
    new Paragraph({
      children: [new TextRun({
        text: `This report reflects the platform state at ${formatDate(data.generated_at)}. ${data.monitoring.active_drift_alerts} active drift alerts; ${data.monitoring.posture_change_alerts} posture-change alerts. A sub-score is excluded (renormalized) when its sample size is zero.`,
        color: COLORS.muted,
      })],
    }),
  ];
}

// ── building blocks ──────────────────────────────────────

function heading(text: string): Paragraph {
  return new Paragraph({
    heading: HeadingLevel.HEADING_1,
    spacing: { before: 240, after: 120 },
    children: [new TextRun({ text, bold: true, size: 32, color: COLORS.accent })],
  });
}

function subheading(text: string): Paragraph {
  return new Paragraph({
    heading: HeadingLevel.HEADING_2,
    spacing: { before: 200, after: 80 },
    children: [new TextRun({ text, bold: true, size: 24, color: COLORS.primary })],
  });
}

function kv(key: string, value: string): Paragraph {
  return new Paragraph({
    spacing: { before: 80 },
    children: [
      new TextRun({ text: `${key}: `, bold: true, size: 22 }),
      new TextRun({ text: value, size: 22 }),
    ],
  });
}

function bullet(text: string): Paragraph {
  return new Paragraph({
    bullet: { level: 0 },
    children: [new TextRun({ text, font: 'Courier New', size: 20 })],
  });
}

function spacer(lines: number): Paragraph {
  return new Paragraph({ children: [new TextRun({ text: ' '.repeat(1) })], spacing: { before: lines * 60, after: lines * 60 } });
}

function keyFigureTable(rows: Array<[string, string, string]>): Table {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        children: rows.map(([, v, color]) => new TableCell({
          width: { size: 25, type: WidthType.PERCENTAGE },
          shading: { type: ShadingType.CLEAR, fill: 'f1f5f9' },
          children: [new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [new TextRun({ text: v, bold: true, size: 40, color })],
          })],
        })),
      }),
      new TableRow({
        children: rows.map(([k]) => new TableCell({
          shading: { type: ShadingType.CLEAR, fill: 'f1f5f9' },
          children: [new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [new TextRun({ text: k, size: 18, color: COLORS.muted })],
          })],
        })),
      }),
    ],
  });
}

function familyBreakdownTable(families: ReportData['family_breakdown']): Table {
  const header = ['Family', 'Score', 'Implemented', 'Total'];
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      headerRow(header),
      ...families.map((f) => new TableRow({
        children: [
          textCell(f.family),
          textCell(`${f.score.toFixed(0)}%`, colorForScore(f.score), true),
          textCell(String(f.implemented)),
          textCell(String(f.total - f.not_applicable)),
        ],
      })),
    ],
  });
}

function trendTable(points: ReportData['trend']): Table {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      headerRow(['Date', 'Overall Score']),
      ...points.map((p) => new TableRow({
        children: [
          textCell(formatDate(p.calculated_at)),
          textCell(p.overall_score.toFixed(1), colorForScore(p.overall_score), true),
        ],
      })),
    ],
  });
}

function controlTable(controls: ReportControlRow[]): Table {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      headerRow(['Control', 'Family', 'Status', 'Evidence', 'Assessment', 'Last Collected']),
      ...controls.map((row) => new TableRow({
        children: [
          textCell(row.control_id),
          textCell(row.family || '—'),
          textCell(row.impl_status ?? 'not-set', statusColor(row.impl_status), true),
          textCell(`${row.evidence_fresh}/${row.evidence_count}`),
          textCell(row.assessment_result ?? '—', assessmentColor(row.assessment_result), true),
          textCell(row.latest_evidence_at ? formatDate(row.latest_evidence_at) : '—'),
        ],
      })),
    ],
  });
}

function summaryTable(rows: Array<[string, string]>): Table {
  return new Table({
    width: { size: 60, type: WidthType.PERCENTAGE },
    rows: rows.map(([k, v]) => new TableRow({
      children: [
        new TableCell({
          width: { size: 70, type: WidthType.PERCENTAGE },
          children: [new Paragraph({ children: [new TextRun({ text: k, color: COLORS.muted })] })],
        }),
        new TableCell({
          width: { size: 30, type: WidthType.PERCENTAGE },
          children: [new Paragraph({
            alignment: AlignmentType.END,
            children: [new TextRun({ text: v, bold: true })],
          })],
        }),
      ],
    })),
  });
}

function riskTable(risks: ReportData['risks']['top']): Table {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      headerRow(['ID', 'Title', 'Inherent', 'Owner']),
      ...risks.map((r) => new TableRow({
        children: [
          textCell(r.risk_id),
          textCell(r.title.substring(0, 80)),
          textCell(String(r.inherent_risk_score), riskColor(r.inherent_risk_score), true),
          textCell(r.owner),
        ],
      })),
    ],
  });
}

function poamTable(items: ReportData['poam']['items']): Table {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      headerRow(['POA&M', 'Control', 'Priority', 'Finding', 'Target']),
      ...items.map((p) => new TableRow({
        children: [
          textCell(p.poam_id),
          textCell(p.control_native_id),
          textCell(p.priority, priorityColor(p.priority), true),
          textCell(p.finding.substring(0, 80)),
          textCell(p.target_date ?? '—', p.overdue ? COLORS.red : undefined),
        ],
      })),
    ],
  });
}

function headerRow(labels: string[]): TableRow {
  return new TableRow({
    tableHeader: true,
    children: labels.map((l) => new TableCell({
      shading: { type: ShadingType.CLEAR, fill: COLORS.headerBg },
      children: [new Paragraph({ children: [new TextRun({ text: l.toUpperCase(), bold: true, size: 16, color: COLORS.primary })] })],
    })),
  });
}

function textCell(text: string, color?: string, bold = false): TableCell {
  return new TableCell({
    children: [new Paragraph({
      children: [new TextRun({ text, color: color ?? COLORS.primary, bold, size: 18 })],
    })],
    borders: allBorders(),
  });
}

function allBorders() {
  const b = { style: BorderStyle.SINGLE, size: 2, color: COLORS.border };
  return { top: b, bottom: b, left: b, right: b };
}

// ── colors ────────────────────────────────────────────────

function colorForScore(n: number | null): string {
  if (n === null) return COLORS.muted;
  if (n >= 80) return COLORS.green;
  if (n >= 60) return COLORS.amber;
  return COLORS.red;
}

function statusColor(status: string | null): string {
  switch (status) {
    case 'implemented': case 'alternative': return COLORS.green;
    case 'partially-implemented': case 'planned': return COLORS.amber;
    case 'not-implemented': return COLORS.red;
    default: return COLORS.muted;
  }
}

function assessmentColor(result: string | null): string {
  switch (result) {
    case 'satisfied': return COLORS.green;
    case 'partial': return COLORS.amber;
    case 'not-satisfied': return COLORS.red;
    default: return COLORS.muted;
  }
}

function riskColor(score: number): string {
  if (score >= 15) return COLORS.red;
  if (score >= 9) return COLORS.amber;
  return COLORS.green;
}

function priorityColor(priority: string): string {
  if (priority === 'critical' || priority === 'high') return COLORS.red;
  if (priority === 'medium') return COLORS.amber;
  return COLORS.muted;
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' });
}
