import * as fs from 'fs';
import * as path from 'path';
import PDFDocument from 'pdfkit';
import type { ReportData } from '../services/reports/aggregate.js';

/**
 * Phase 8C — Audit-grade PDF report.
 *
 * Produces a polished compliance audit report from ReportData. Layout:
 *   1. Cover page
 *   2. Executive summary (overall score, KPIs, trend sparkline)
 *   3. Control inventory (table)
 *   4. Evidence + Risk + POA&M summary
 *   5. Appendix — methodology + scoring weights
 *
 * pdfkit is streaming so we use event-based completion.
 */

const COLORS = {
  primary: '#1e293b',
  muted: '#64748b',
  border: '#cbd5e1',
  green: '#16a34a',
  amber: '#d97706',
  red: '#dc2626',
  accent: '#4338ca',
};

export interface PdfResult {
  path: string;
  bytes: number;
  pages: number;
}

export function renderAuditReportPdf(
  data: ReportData,
  outputPath: string,
): Promise<PdfResult> {
  return new Promise((resolve, reject) => {
    const resolved = path.resolve(outputPath);
    const doc = new PDFDocument({
      size: 'LETTER',
      margin: 54,
      bufferPages: true,
      info: {
        Title: `Compliance Audit Report — ${data.catalog.name}`,
        Author: 'Attesting',
        Subject: `${data.organization.name} / ${data.scope.name}`,
        CreationDate: new Date(data.generated_at),
      },
    });
    const stream = fs.createWriteStream(resolved);
    doc.pipe(stream);

    renderCoverPage(doc, data);
    doc.addPage();
    renderExecutiveSummary(doc, data);
    doc.addPage();
    renderControlInventory(doc, data);
    doc.addPage();
    renderSubsystems(doc, data);
    doc.addPage();
    renderAppendix(doc, data);

    applyFooters(doc, data);

    const pages = doc.bufferedPageRange().count;

    stream.on('finish', () => {
      const bytes = fs.statSync(resolved).size;
      resolve({ path: resolved, bytes, pages });
    });
    stream.on('error', reject);
    doc.end();
  });
}

// ── Pages ─────────────────────────────────────────────────

function renderCoverPage(doc: PDFKit.PDFDocument, data: ReportData): void {
  const y = 150;
  doc.fillColor(COLORS.accent)
    .rect(54, y - 40, 504, 4)
    .fill();
  doc.fillColor(COLORS.primary)
    .font('Helvetica-Bold').fontSize(28)
    .text('Compliance Audit Report', 54, y, { align: 'left' });

  doc.moveDown(0.4);
  doc.font('Helvetica').fontSize(16).fillColor(COLORS.muted)
    .text(data.catalog.name);

  doc.moveDown(2);
  doc.fontSize(11).fillColor(COLORS.primary);
  doc.font('Helvetica-Bold').text('Organization: ', { continued: true })
     .font('Helvetica').text(data.organization.name);
  doc.font('Helvetica-Bold').text('Scope: ', { continued: true })
     .font('Helvetica').text(data.scope.name);
  doc.font('Helvetica-Bold').text('Catalog: ', { continued: true })
     .font('Helvetica').text(`${data.catalog.name} (${data.catalog.short_name})`);
  doc.font('Helvetica-Bold').text('Generated: ', { continued: true })
     .font('Helvetica').text(formatDate(data.generated_at));
  doc.font('Helvetica-Bold').text('Total Controls: ', { continued: true })
     .font('Helvetica').text(String(data.catalog.total_controls || data.controls.length));

  // Big score block
  const score = data.score?.overall_score ?? 0;
  const scoreColor = colorForScore(score);

  const boxY = 440;
  doc.roundedRect(54, boxY, 504, 120, 8)
    .fillColor('#f8fafc').fill();
  doc.fillColor(scoreColor)
    .font('Helvetica-Bold').fontSize(72)
    .text(score.toFixed(0), 54, boxY + 20, { align: 'center', width: 504 });
  doc.fillColor(COLORS.muted)
    .font('Helvetica').fontSize(11)
    .text('Overall Compliance Score (0–100)', 54, boxY + 96, { align: 'center', width: 504 });

  doc.fillColor(COLORS.muted).fontSize(9)
    .text('Generated by Attesting. This document is produced from live compliance state and may contain sensitive information.', 54, 720, { align: 'center', width: 504 });
}

function renderExecutiveSummary(doc: PDFKit.PDFDocument, data: ReportData): void {
  sectionHeader(doc, '1. Executive Summary');

  const s = data.score;
  const kpis: Array<[string, string, string]> = [
    ['Overall Score', `${(s?.overall_score ?? 0).toFixed(1)}`, colorForScore(s?.overall_score ?? 0)],
    ['Coverage',      `${(s?.coverage_score ?? 0).toFixed(1)}`, colorForScore(s?.coverage_score ?? 0)],
    ['Evidence',      s?.evidence_score !== null && s?.evidence_score !== undefined ? `${s.evidence_score.toFixed(1)}` : 'n/a', colorForScore(s?.evidence_score ?? null)],
    ['Assessment',    s?.assessment_score !== null && s?.assessment_score !== undefined ? `${s.assessment_score.toFixed(1)}` : 'n/a', colorForScore(s?.assessment_score ?? null)],
  ];

  const kpiY = doc.y + 10;
  const tileWidth = 118;
  kpis.forEach(([label, value, color], i) => {
    const x = 54 + i * (tileWidth + 6);
    doc.roundedRect(x, kpiY, tileWidth, 70, 6).fillColor('#f1f5f9').fill();
    doc.fillColor(color).font('Helvetica-Bold').fontSize(22)
      .text(value, x, kpiY + 12, { width: tileWidth, align: 'center' });
    doc.fillColor(COLORS.muted).font('Helvetica').fontSize(9)
      .text(label, x, kpiY + 48, { width: tileWidth, align: 'center' });
  });
  doc.y = kpiY + 90;

  // Per-family breakdown
  doc.moveDown(1);
  doc.fillColor(COLORS.primary).font('Helvetica-Bold').fontSize(12).text('Control Family Breakdown');
  doc.moveDown(0.3);

  const families = data.family_breakdown ?? [];
  if (families.length === 0) {
    doc.font('Helvetica').fontSize(10).fillColor(COLORS.muted)
      .text('No family breakdown available.');
  } else {
    doc.font('Helvetica').fontSize(9).fillColor(COLORS.primary);
    for (const f of families.slice(0, 18)) {
      const pct = f.score.toFixed(0) + '%';
      const barWidth = 200;
      const fillWidth = (f.score / 100) * barWidth;
      const y = doc.y;
      doc.text(f.family.padEnd(20).slice(0, 20), 54, y, { continued: false });
      doc.rect(220, y, barWidth, 10).strokeColor(COLORS.border).lineWidth(0.5).stroke();
      doc.rect(220, y, fillWidth, 10).fillColor(colorForScore(f.score)).fill();
      doc.fillColor(COLORS.primary)
        .text(pct, 430, y, { width: 40, align: 'right' });
      doc.text(`${f.implemented}/${f.total - f.not_applicable}`, 480, y, { width: 60, align: 'right' });
      doc.moveDown(0.25);
    }
  }

  // Trend
  doc.moveDown(0.8);
  doc.fillColor(COLORS.primary).font('Helvetica-Bold').fontSize(12)
    .text(`Score Trend (last ${data.trend.length} snapshot${data.trend.length === 1 ? '' : 's'})`);
  doc.moveDown(0.3);

  if (data.trend.length < 2) {
    doc.font('Helvetica').fontSize(10).fillColor(COLORS.muted)
      .text('Not enough history for a trend line. Take more snapshots to populate.');
  } else {
    drawSparkline(doc, data.trend.map((p) => p.overall_score), 54, doc.y, 504, 50);
    doc.y += 60;
    const first = data.trend[0].overall_score;
    const last = data.trend[data.trend.length - 1].overall_score;
    const delta = last - first;
    doc.font('Helvetica').fontSize(9).fillColor(COLORS.muted)
      .text(`From ${formatDate(data.trend[0].calculated_at)} → ${formatDate(data.trend[data.trend.length - 1].calculated_at)}  ·  Δ ${delta >= 0 ? '+' : ''}${delta.toFixed(1)} points`);
  }
}

function renderControlInventory(doc: PDFKit.PDFDocument, data: ReportData): void {
  sectionHeader(doc, '2. Control Inventory');
  doc.font('Helvetica').fontSize(9).fillColor(COLORS.muted)
    .text(`${data.controls.length} controls total. Implementation status per control with evidence and assessment summary.`);
  doc.moveDown(0.5);

  const cols = [
    { label: 'Control',     x: 54,  w: 80 },
    { label: 'Family',      x: 134, w: 70 },
    { label: 'Status',      x: 204, w: 90 },
    { label: 'Evidence',    x: 294, w: 70 },
    { label: 'Assessment',  x: 364, w: 90 },
    { label: 'Last Coll.',  x: 454, w: 100 },
  ];
  drawTableHeader(doc, cols);
  doc.font('Helvetica').fontSize(8);

  for (const row of data.controls) {
    if (doc.y > 720) {
      doc.addPage();
      drawTableHeader(doc, cols);
      doc.font('Helvetica').fontSize(8);
    }
    const y = doc.y;
    doc.fillColor(COLORS.primary).text(row.control_id, cols[0].x, y, { width: cols[0].w - 4 });
    doc.fillColor(COLORS.muted).text(row.family || '—', cols[1].x, y, { width: cols[1].w - 4 });
    doc.fillColor(statusColor(row.impl_status)).text(row.impl_status ?? 'not-set', cols[2].x, y, { width: cols[2].w - 4 });
    doc.fillColor(COLORS.primary).text(
      `${row.evidence_fresh}/${row.evidence_count}`,
      cols[3].x, y, { width: cols[3].w - 4 },
    );
    doc.fillColor(assessmentColor(row.assessment_result))
      .text(row.assessment_result ?? '—', cols[4].x, y, { width: cols[4].w - 4 });
    doc.fillColor(COLORS.muted).text(
      row.latest_evidence_at ? formatDate(row.latest_evidence_at) : '—',
      cols[5].x, y, { width: cols[5].w - 4 },
    );
    doc.moveDown(0.55);
    doc.strokeColor(COLORS.border).lineWidth(0.25)
      .moveTo(54, doc.y - 2).lineTo(558, doc.y - 2).stroke();
  }
}

function renderSubsystems(doc: PDFKit.PDFDocument, data: ReportData): void {
  sectionHeader(doc, '3. Evidence, Risk & POA&M');

  // Evidence block
  subHeader(doc, '3.1  Evidence Summary');
  const es = data.evidence_summary;
  twoCol(doc, [
    ['Total Artifacts',         String(es.total)],
    ['Fresh',                   String(es.fresh)],
    ['Expiring Soon',           String(es.expiring_soon)],
    ['Expired',                 String(es.expired)],
    ['Pending Review',          String(es.pending)],
    ['Rejected',                String(es.rejected)],
    ['Controls with Evidence',  String(es.controls_with_evidence)],
    ['Controls Missing',        String(es.controls_missing_evidence)],
  ]);
  doc.moveDown(0.8);

  // Risk block
  subHeader(doc, '3.2  Risk Summary');
  doc.font('Helvetica').fontSize(10).fillColor(COLORS.primary)
    .text(`${data.risks.total_open} open risk${data.risks.total_open === 1 ? '' : 's'}. Top items by inherent score:`);
  doc.moveDown(0.3);
  if (data.risks.top.length === 0) {
    doc.fillColor(COLORS.muted).fontSize(9).text('No open risks.');
  } else {
    doc.font('Helvetica').fontSize(9);
    for (const r of data.risks.top) {
      const y = doc.y;
      doc.fillColor(COLORS.primary).text(r.risk_id, 54, y, { width: 60 });
      doc.text(r.title.substring(0, 70), 120, y, { width: 300 });
      doc.fillColor(riskColor(r.inherent_risk_score))
        .text(String(r.inherent_risk_score), 420, y, { width: 40, align: 'right' });
      doc.fillColor(COLORS.muted).text(r.owner, 470, y, { width: 90 });
      doc.moveDown(0.35);
    }
  }
  doc.moveDown(0.8);

  // POA&M block
  subHeader(doc, '3.3  POA&M Items');
  doc.font('Helvetica').fontSize(10).fillColor(COLORS.primary)
    .text(`${data.poam.total_open} open item${data.poam.total_open === 1 ? '' : 's'}, ${data.poam.overdue} overdue.`);
  doc.moveDown(0.3);
  if (data.poam.items.length === 0) {
    doc.fillColor(COLORS.muted).fontSize(9).text('No open POA&M items.');
  } else {
    doc.font('Helvetica').fontSize(9);
    for (const item of data.poam.items.slice(0, 15)) {
      const y = doc.y;
      doc.fillColor(COLORS.primary).text(item.poam_id, 54, y, { width: 60 });
      doc.text(item.control_native_id, 120, y, { width: 60 });
      doc.fillColor(priorityColor(item.priority)).text(item.priority, 180, y, { width: 60 });
      doc.fillColor(COLORS.primary).text(item.finding.substring(0, 65), 240, y, { width: 250 });
      doc.fillColor(item.overdue ? COLORS.red : COLORS.muted)
        .text(item.target_date ?? '—', 490, y, { width: 70 });
      doc.moveDown(0.35);
    }
  }
}

function renderAppendix(doc: PDFKit.PDFDocument, data: ReportData): void {
  sectionHeader(doc, '4. Appendix — Methodology');

  const m = data.methodology;
  doc.font('Helvetica').fontSize(10).fillColor(COLORS.primary)
    .text('Attesting calculates compliance scores using a three-factor weighted formula:')
    .moveDown(0.5);

  doc.font('Courier').fontSize(10)
    .text(`  overall = coverage × ${m.coverage_weight.toFixed(2)}`)
    .text(`          + evidence × ${m.evidence_weight.toFixed(2)}`)
    .text(`          + assessment × ${m.assessment_weight.toFixed(2)}`);
  doc.moveDown(0.5);

  doc.font('Helvetica').fontSize(10).fillColor(COLORS.primary).text('Coverage factor weights:').moveDown(0.2);
  doc.font('Helvetica').fontSize(9).fillColor(COLORS.muted)
    .text('  implemented            1.00')
    .text('  alternative            0.75')
    .text('  partially-implemented  0.50')
    .text('  planned                0.25')
    .text('  not-implemented        0.00')
    .text('  not-applicable         excluded');

  doc.moveDown(0.6);
  doc.font('Helvetica').fontSize(10).fillColor(COLORS.primary)
    .text(`Evidence freshness window: ${m.evidence_fresh_days} days.`);
  doc.moveDown(0.3);
  doc.font('Helvetica').fontSize(9).fillColor(COLORS.muted)
    .text('A sub-score is excluded (renormalized) when its sample size is zero. Scores are averaged across scopes and catalogs at the executive summary level.');

  doc.moveDown(1);
  doc.font('Helvetica-Bold').fontSize(10).fillColor(COLORS.primary).text('Data Provenance');
  doc.moveDown(0.2);
  doc.font('Helvetica').fontSize(9).fillColor(COLORS.muted)
    .text(`This report reflects the platform state at ${formatDate(data.generated_at)}. Drift alerts (${data.monitoring.active_drift_alerts} active, ${data.monitoring.posture_change_alerts} posture-change) and evidence lifecycle state changes continuously update the underlying data.`);
}

// ── primitives ────────────────────────────────────────────

function sectionHeader(doc: PDFKit.PDFDocument, text: string): void {
  doc.fillColor(COLORS.accent).font('Helvetica-Bold').fontSize(16).text(text);
  doc.strokeColor(COLORS.accent).lineWidth(1.5)
    .moveTo(54, doc.y + 2).lineTo(558, doc.y + 2).stroke();
  doc.moveDown(0.6);
  doc.fillColor(COLORS.primary);
}

function subHeader(doc: PDFKit.PDFDocument, text: string): void {
  doc.fillColor(COLORS.primary).font('Helvetica-Bold').fontSize(12).text(text);
  doc.moveDown(0.3);
}

function drawTableHeader(
  doc: PDFKit.PDFDocument,
  cols: Array<{ label: string; x: number; w: number }>,
): void {
  doc.font('Helvetica-Bold').fontSize(8).fillColor(COLORS.muted);
  const y = doc.y;
  for (const c of cols) doc.text(c.label.toUpperCase(), c.x, y, { width: c.w - 4 });
  doc.moveDown(0.4);
  doc.strokeColor(COLORS.border).lineWidth(0.75)
    .moveTo(54, doc.y).lineTo(558, doc.y).stroke();
  doc.moveDown(0.2);
}

function twoCol(doc: PDFKit.PDFDocument, rows: Array<[string, string]>): void {
  doc.font('Helvetica').fontSize(9);
  const mid = Math.ceil(rows.length / 2);
  const col1 = rows.slice(0, mid);
  const col2 = rows.slice(mid);
  const startY = doc.y;
  let y = startY;
  for (const [k, v] of col1) {
    doc.fillColor(COLORS.muted).text(k, 60, y, { width: 160 });
    doc.fillColor(COLORS.primary).text(v, 220, y, { width: 60, align: 'right' });
    y += 14;
  }
  let y2 = startY;
  for (const [k, v] of col2) {
    doc.fillColor(COLORS.muted).text(k, 310, y2, { width: 160 });
    doc.fillColor(COLORS.primary).text(v, 470, y2, { width: 60, align: 'right' });
    y2 += 14;
  }
  doc.y = Math.max(y, y2);
}

function drawSparkline(
  doc: PDFKit.PDFDocument,
  values: number[],
  x: number, y: number, w: number, h: number,
): void {
  if (values.length < 2) return;
  const min = Math.min(...values);
  const max = Math.max(...values);
  const range = Math.max(1, max - min);
  doc.strokeColor(COLORS.border).lineWidth(0.5).rect(x, y, w, h).stroke();
  doc.strokeColor(COLORS.accent).lineWidth(1.5);
  values.forEach((v, i) => {
    const px = x + (i / (values.length - 1)) * w;
    const py = y + h - ((v - min) / range) * h;
    if (i === 0) doc.moveTo(px, py);
    else doc.lineTo(px, py);
  });
  doc.stroke();
}

function applyFooters(doc: PDFKit.PDFDocument, data: ReportData): void {
  const range = doc.bufferedPageRange();
  for (let i = 0; i < range.count; i++) {
    doc.switchToPage(range.start + i);
    doc.font('Helvetica').fontSize(8).fillColor(COLORS.muted);
    doc.text(
      `${data.organization.name} · ${data.catalog.short_name} · Page ${i + 1} of ${range.count}`,
      54, 760, { align: 'center', width: 504, lineBreak: false },
    );
  }
}

// ── color mapping ─────────────────────────────────────────

function colorForScore(n: number | null): string {
  if (n === null) return COLORS.muted;
  if (n >= 80) return COLORS.green;
  if (n >= 60) return COLORS.amber;
  return COLORS.red;
}

function statusColor(status: string | null): string {
  switch (status) {
    case 'implemented':           return COLORS.green;
    case 'alternative':           return COLORS.green;
    case 'partially-implemented': return COLORS.amber;
    case 'planned':               return COLORS.amber;
    case 'not-applicable':        return COLORS.muted;
    case 'not-implemented':       return COLORS.red;
    default:                      return COLORS.muted;
  }
}

function assessmentColor(result: string | null): string {
  switch (result) {
    case 'satisfied':      return COLORS.green;
    case 'partial':        return COLORS.amber;
    case 'not-satisfied':  return COLORS.red;
    case 'not-applicable': return COLORS.muted;
    default:               return COLORS.muted;
  }
}

function riskColor(score: number): string {
  if (score >= 20) return COLORS.red;
  if (score >= 15) return COLORS.red;
  if (score >= 9)  return COLORS.amber;
  return COLORS.green;
}

function priorityColor(priority: string): string {
  switch (priority) {
    case 'critical': return COLORS.red;
    case 'high':     return COLORS.red;
    case 'medium':   return COLORS.amber;
    default:         return COLORS.muted;
  }
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' });
}
